services:
  - type: web
    name: orderlybot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python OrderlyBot.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: orderlybot-db
          property: connectionString