services:
  - type: web
    name: orderlybot
    runtime: python
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python OrderlyBot.py
    pythonVersion: 3.11.8